Fix CODEBUILD_SOURCE_VERSION matching (#102)
According to AWS CodeBuild User Guide,
CODEBUILD_SOURCE_VERSION depends on the source repository.
When build is triggered by a webhook pull request event,
the value is pull_request number(pr/xxx)
otherwise the value is other than pull request number(commit id, branch name
or tag name).

In the latter case, an error raises like below.

```
/root/caches/vendor/bundle/ruby/2.5.0/gems/codecov-0.2.11/lib/codecov.rb:171
:in `build_params': undefined method `[]' for nil:NilClass (NoMethodError)
```